const regulamin_systemu_prowizyjnego = {
    header: 'Regulamin Systemu Prowizyjnego Akademii Edukacyjnej GoldSkill',
    sections: [
        {header: '§1. Postanowienia ogólne', texts: ['1.1 Niniejszy Regulamin ("Regulamin") określa zasady uczestnictwa w systemie prowizyjnym Akademii Edukacyjnej GoldSkill ("Akademia"), który oparty jest na promocji usług edukacyjnych związanych z rynkiem Forex, tradingiem oraz inwestycjami.', '1.2. System prowizyjny jest dostępny wyłącznie dla Partnerów, którzy posiadają pełną zdolność do czynności prawnych oraz spełniają warunki określone w niniejszym Regulaminie.']},
        {header: '§2. Warunki uczestnictwa w systemie prowizyjnym', texts: ['2.1. Aby uczestniczyć w systemie prowizyjnym, Partner musi posiadać aktywne konto na stronie internetowej Akademii i zaakceptować niniejszy Regulamin poprzez zaznaczenie odpowiedniego pola podczas rejestracji.', '2.2. Partner zobowiązuje się do wykorzystywania usług edukacyjnych Akademii wyłącznie w celach promujących dostęp do usług, a nie do obiecywania zysków finansowych lub innych niezgodnych z regulaminem działań.', '2.3. Aby otrzymać prowizję, Partner musi wystawić fakturę lub rachunek na sprzedaż usług edukacyjnych, niezależnie od tego, czy prowadzi działalność gospodarczą, czy też nie.', '2.4. Partner zobowiązuje się do przestrzegania przepisów prawa polskiego, w tym przepisów dotyczących ochrony danych osobowych, reklamacji oraz zgodności z regulacjami KNF (Komisja Nadzoru Finansowego).']},
        {header: '§3. System prowizyjny', texts: ['3.1. Akademia oferuje system prowizyjny dla Partnerów promujących dostęp do usług edukacyjnych związanych z rynkiem Forex, tradingiem i inwestycjami.', '3.2. Partnerzy mogą uzyskać prowizje w następującej wysokości:', '- 50% za pierwszą rejestrację (bezpośrednia sprzedaż),', '- 20% za przedłużenie subskrypcji,', '- 10% za wprowadzenie klienta przez osoby z drugiego poziomu struktury,', '- 5% za wprowadzenie klienta przez osoby z trzeciego poziomu struktury.', '3.3. Prowizje są wypłacane wyłącznie za rzeczywistą sprzedaż dostępu do usług edukacyjnych Akademii, a nie za samą rekrutację nowych Partnerów. Prowizje są naliczane od ceny netto sprzedaży.', '3.4. Prowizje wypłacane są po upływie okresu zwrotu dla klienta (14 dni), pod warunkiem, że klient nie odstąpił od umowy i nie zażądał zwrotu pieniędzy.']},
        {header: '§4. Zasady wypłaty prowizji', texts: ['4.1. Prowizje będą wypłacane Partnerom na wskazany przez nich rachunek bankowy po zakończeniu okresu zwrotu dla klienta, na warunkach określonych w §3.', '4.2. Wypłata prowizji następuje najpóźniej w terminie 30 dni roboczych od upływu okresu zwrotu, pod warunkiem, że klient nie odstąpił od umowy. Planowana data wypłat przypada na dziesiąty dzień każdego miesiąca, przy założeniu, że okres rezygnacji zakończył się w poprzednim miesiącu.', '4.3. Prowizje są naliczane od ceny netto sprzedaży i nie obejmują podatku VAT, który może być naliczany w zależności od statusu podatkowego Partnera.', '4.4. Partnerzy są zobowiązani do wystawienia faktury lub rachunku za każdą transakcję, niezależnie od tego, czy prowadzą działalność gospodarczą, czy też nie. W przypadku Partnerów nieprowadzących działalności gospodarczej, faktura będzie wystawiona w formie faktury "osoba fizyczna" lub innej zgodnej z obowiązującymi przepisami prawa.']},
        {header: '§5. Wgląd w dane osobowe', texts: ['5.1. Partnerzy wyrażają zgodę na udostępnienie ich danych osobowych (imię oraz nazwisko) osobie, która ich zarejestrowała w systemie Akademii ("osoba polecająca"), celem wygenerowania raportu o aktualnym stanie struktury oraz monitorowania wyników sprzedaży.', '5.2. Osoba polecająca, która zarejestrowała Partnera, będzie miała dostęp do danych dotyczących struktur partnerskich, w tym informacji o liczbie zarejestrowanych użytkowników, sprzedaży usług edukacyjnych i osiągniętych prowizjach.', '5.3. Administracja Akademii zastrzega sobie prawo do przetwarzania danych osobowych w celach związanych z realizacją usług edukacyjnych oraz zapewnienia prawidłowego funkcjonowania systemu prowizyjnego. Wszystkie dane przetwarzane są zgodnie z Polityką Prywatności i przepisami o ochronie danych osobowych (RODO).']},
        {header: '§6. Odpowiedzialność Partnerów', texts: ['6.1. Partnerzy ponoszą pełną odpowiedzialność za zgodność z prawem wszelkich działań związanych z promocją Akademii, w tym z przestrzeganiem przepisów o ochronie danych osobowych, praw konsumentów, przepisów podatkowych oraz przepisów o nieuczciwej konkurencji.', '6.2. Partnerzy zobowiązują się do unikania działań mogących naruszać dobre imię Akademii, w tym obiecywania zysków finansowych, wprowadzania w błąd klientów, czy stosowania nieuczciwych praktyk marketingowych.', '6.3. Akademia zastrzega sobie prawo do usunięcia Partnera z systemu prowizyjnego oraz do odmowy wypłaty prowizji, jeśli Partner naruszy przepisy Regulaminu lub działanie Partnera narazi Akademię na straty finansowe lub prawne.']},
        {header: '§7. Zmiany Regulaminu', texts: ['7.1. Akademia zastrzega sobie prawo do zmiany niniejszego Regulaminu w dowolnym czasie. Zmiany będą komunikowane Partnerom za pośrednictwem e-maila lub poprzez kanał nadawczy Akademii.','7.2. Zmiany w Regulaminie wchodzą w życie w terminie wskazanym w ogłoszeniu, a brak akceptacji zmienionych warunków będzie skutkowało rozwiązaniem umowy o uczestnictwo w systemie prowizyjnym poprzez e-mail partnera o rezygnacji.']},
        {header: '§8. Postanowienia końcowe', texts: ['8.1. Regulamin wchodzi w życie z dniem 01.03.2025 rok.', '8.2. W sprawach nieuregulowanych niniejszym Regulaminem zastosowanie mają przepisy prawa polskiego oraz regulacje Komisji Nadzoru Finansowego (KNF), w szczególności przepisy dotyczące usług edukacyjnych związanych z rynkiem Forex i inwestycjami.', '8.3. Akademia zastrzega sobie prawo do usunięcia Partnera z systemu prowizyjnego w przypadku, gdy będzie to konieczne w celu zachowania zgodności z obowiązującymi przepisami prawa lub regulacjami KNF.']}
    ]
} as {
    header: string,
  sections: {header: string, texts: string[]}[]
}


export default regulamin_systemu_prowizyjnego;
