
const regulamin = {
    header: 'Regulamin korzystania z usług Akademii Edukacyjnej GoldSkill',
    sections: [
        {header: '§1. Postanowienia ogólne', texts: ['1.1. Niniejszy Regulamin („Regulamin”) określa zasady korzystania z usług edukacyjnych oferowanych przez Akademię GoldSkill („Akademia”), dostępnym za pośrednictwem strony internetowej goldskill.pl.', '1.2. Usługi Akademii polegają na świadczeniu dostępu do materiałów edukacyjnych dotyczących rynku Forex oraz szkoleń, sesji edukacyjnych i webinarów związanych z tematyką inwestycji.', '1.3. Akademia nie świadczy usług doradztwa inwestycyjnego ani innych usług objętych nadzorem Komisji Nadzoru Finansowego (KNF), w tym usług maklerskich lub inwestycyjnych.', '1.4. Z usługi mogą korzystać osoby, które ukończyły 18. rok życia i mają pełną zdolność do czynności prawnych.']},
        {header: '§2. Charakter działalności', texts: ['2.1. Wszystkie treści i materiały udostępniane przez Akademię mają wyłącznie charakter edukacyjny i służą poszerzeniu wiedzy uczestników.', '2.2. Akademia nie gwarantuje żadnych wyników finansowych wynikających z wykorzystania wiedzy zdobytej podczas kursów, szkoleń lub innych materiałów edukacyjnych.', '2.3. Wszelkie informacje i porady udzielane w ramach usług edukacyjnych mają charakter ogólny i nie stanowią rekomendacji inwestycyjnych.']},
        {header: '§3. Zasady korzystania z usług', texts: ['3.1. Klienci mogą uzyskać dostęp do zamkniętej grupy edukacyjnej po opłaceniu jednorazowego abonamentu na okres [miesiąc, pół roku, rok].', '3.2. Uczestnik zobowiązuje się do wykorzystywania materiałów Akademii wyłącznie na własny użytek edukacyjny.', '3.3. Zabrania się wykorzystywania treści edukacyjnych w celach rekomendacyjnych, komercyjnych lub doradczych wobec osób trzecich.']},
        {header: '§4. Zakaz promowania zewnętrznych podmiotów', texts: ['4.1 W Akademii GoldSkill obowiązuje bezwzględny zakaz promowania jakichkolwiek produktów, usług lub grup zewnętrznych, które nie są bezpośrednio związane z działalnością Akademii. Naruszenie tej zasady skutkować będzie natychmiastowym i bezzwrotnym usunięciem z grupy, a w przypadku poważniejszych naruszeń, może zostać nałożona kara finansowa w wysokości 999 €. W przypadku większych naruszeń, związanych z nieuczciwą konkurencją i poniesionymi stratami, mogą zostać zastosowane dodatkowe sankcje.',]},
        {header: '§5. Oświadczenia prawne', texts: ['5.1. Wszystkie treści edukacyjne i materiały promocyjne Akademii zawierają następujące adnotacje:','- „Treści edukacyjne udostępniane przez Akademię Forex mają wyłącznie charakter informacyjny i edukacyjny. Przeszłe wyniki finansowe nie gwarantują przyszłych rezultatów. Akademia nie świadczy usług doradztwa inwestycyjnego ani maklerskich.”','Akademia nie prowadzi działalności wymagającej zezwoleń Komisji Nadzoru Finansowego (KNF) ani nie pośredniczy w takich usługach. Wszystkie oferowane usługi mają charakter edukacyjny i informacyjny, a ich celem jest rozwój wiedzy uczestników.', '5.2. Edukatorzy prowadzący sesje edukacyjne zobowiązani są na początku każdej sesji poinformować uczestników, że:','- Treści przedstawiane w trakcie szkolenia nie stanowią rekomendacji inwestycyjnych.','- Akademia nie bierze odpowiedzialności za decyzje inwestycyjne podejmowane przez uczestników na podstawie zdobytej wiedzy.']},
        {header: '§6. Ochrona danych osobowych (RODO)', texts: ['6.1. Administratorem danych osobowych uczestników jest Akademia Forex z siedzibą w Polska, 87-200 Wąbrzeźno, M. Rataja 46.', '6.2. Dane osobowe przetwarzane są w celu realizacji usług edukacyjnych, zawarcia i wykonania umowy oraz w celach marketingowych, o ile użytkownik wyraził na to zgodę. Dane osobowe są przechowywane przez okres niezbędny do realizacji celów związanych z systemem prowizyjnym, zgodnie z Polityką Prywatności Akademii dostępną na stronie internetowej.', '6.3. Uczestnikom przysługuje prawo dostępu do swoich danych, ich sprostowania, usunięcia, ograniczenia przetwarzania, a także prawo do przenoszenia danych. Kontakt w tej sprawie można nawiązać pod adresem: biuro@goldskill.pl.', '6.4. Szczegóły dotyczące ochrony danych osobowych zawarte są w Polityce Prywatności dostępnej na stronie internetowej Akademii.']},
        {header: '§7. Zasady reklamacji i odstąpienia od umowy', texts: ['7.1. Uczestnik ma prawo do odstąpienia od umowy w ciągu 14 dni od daty zakupu dostępu, bez podania przyczyny, zgodnie z Ustawą o prawach konsumenta.', '7.2. Reklamacje dotyczące usług edukacyjnych można zgłaszać za pośrednictwem adresu e-mail: biuro@goldskill.pl.','7.3. Reklamacje będą rozpatrywane w ciągu 14 dni roboczych od daty ich otrzymania.']},
        {header: '§8. Odpowiedzialność Akademii', texts: ['8.1. Akademia nie ponosi odpowiedzialności za decyzje inwestycyjne podejmowane przez uczestników kursów na podstawie wiedzy zdobytej podczas szkoleń.', '8.2. Akademia nie gwarantuje żadnych wyników finansowych związanych z działalnością na rynku Forex.', '8.3. Akademia nie ponosi odpowiedzialności za straty wynikające z zakłóceń technicznych, siły wyższej ani przerw w dostępie do materiałów edukacyjnych.']},
        {header: '§9. Postanowienia końcowe', texts: ['9.1. Regulamin wchodzi w życie z dniem 01.03.2025.', '9.2. Akademia zastrzega sobie prawo do zmiany regulaminu, przy czym zmiany te będą komunikowane uczestnikom z co najmniej 14-dniowym wyprzedzeniem.', '9.3. W sprawach nieuregulowanych niniejszym regulaminem zastosowanie mają przepisy prawa polskiego.']},
        {header: '§10. Polityka zwrotów', texts: ['10.1. Uczestnik ma prawo do zwrotu opłaty za dostęp do materiałów edukacyjnych w ciągu 14 dni od daty zakupu, pod warunkiem, że nie rozpoczął korzystania z kursu lub materiałów (np. nie brał udziału w sesjach na żywo).', '10.2. Zwrot następuje na podstawie zgłoszenia wysłanego na adres e-mail: biuro@goldskill.pl.', '10.3. Akademia zastrzega sobie prawo do odrzucenia wniosku o zwrot, jeśli uczestnik korzystał z materiałów edukacyjnych w sposób, który wyklucza prawo do zwrotu (udział w sesjach live, wgląd do ,,Zrozumienie Rynków - Kompleksowy Kurs Tradingowy").']},
        {header: '§11. Zasady komunikacji marketingowej', texts: ['11.1. Uczestnicy mogą wyrazić zgodę na otrzymywanie materiałów marketingowych od Akademii.', '11.2. Zgoda na otrzymywanie komunikacji marketingowej może zostać wycofana w dowolnym momencie przez kliknięcie w link „wypisz się” w otrzymanych wiadomościach e-mail.', '11.3. Akademia nie przekazuje danych osobowych uczestników osobom trzecim bez ich wyraźnej zgody.']},
        {header: '§12. Termin dostawy usługi', texts: ['Termin dostawy usługi, tj. dostępu do zamkniętej grupy edukacyjnej GoldSkill na Discord, wynosi do 48 godzin od zaksięgowania płatności. W celu pełnej aktywacji, klient zobowiązany jest do skontaktowania się z działem wsparcia za pośrednictwem Discord, wysyłając potwierdzenie dokonania płatności. Po spełnieniu tych warunków, dostęp do grupy zostanie zaktualizowany w wyznaczonym czasie.']}
    ]
} as {
    header: string,
  sections: {header: string, texts: string[]}[]
}

const regulamin_dodatkowe = {
    header: 'Dodatkowe postanowienia',
    sections: [
        {header: '§13. Zasady przejrzystości i uczciwości', texts: ['12.1. Użytkownik przyjmuje do wiadomości, że inwestowanie na rynku Forex wiąże się z ryzykiem utraty kapitału. Wszystkie usługi edukacyjne oferowane przez Akademię mają na celu jedynie poszerzenie wiedzy i nie stanowią gwarancji zysków.', '12.2. Na stronie internetowej GoldSkill umieszczono odpowiednie ostrzeżenie o ryzyku inwestycyjnym, zgodnie z regulacjami KNF.']},
        {header: '§14. Zasady dotyczące wglądu w dane użytkowników', texts: ['13.1. Użytkownik wyraża zgodę na udostępnienie swoich danych dotyczących aktywności w strukturze administratorowi oraz osobom, które go zarejestrowały',]},
        {header: '§15. Kurs wymiany i płatności', texts: ['14.1. Cennik usług edukacyjnych Akademii podany jest w euro (EUR), a płatności mogą być dokonywane zarówno w euro (EUR), jak i w polskich złotych (PLN), po kursie wymiany 1 EUR = 4,39 PLN.', '14.2. Strony wyrażają zgodę na stosowanie kursu wymiany 1 EUR = 4,39 PLN przy przeliczaniu płatności w EUR na PLN lub odwrotnie.', '14.3. Prowizje dla Partnerów będą wypłacane wyłącznie w polskich złotych (PLN) na wskazane przez Partnera konto bankowe w PLN.']}
    ]
} as {
    header: string,
  sections: {header: string, texts: string[]}[]
}

export default regulamin;
export {regulamin_dodatkowe}